### ISSUE TITLE
Can't find that list

### ISSUE THREAD

**Issue by koehn** [revpriest/listman#10]
When I use the "Link to Native Form" button on a list that I have saved, and submit the name/email/amth problem, here's what I see:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/583888/126002907-0ca76ba0-6138-4215-8c4a-5156342406ec.png">

**Comment by revpriest** [comment]
Couldn't recreate it at first, but seems the problem was with a newly saved list, it's new ID wasn't being saved into the list model until a new list was selected from the left.

So should be fixed with new release just now, even new lists should show the right link and subscribe-form
