### ISSUE TITLE
SMTP setting missing STARTTLS ?

### ISSUE THREAD

**Issue by ledufakademy** [revpriest/listman#16]
i cannot achieve to send mail ...
create a list , members , click on send all : nobody receive mail.

`
Mar  9 00:28:33 mail1 postfix/submission/smtpd[889279]: connect from web2.tld.org[10.10.10.112]
Mar  9 00:28:33 mail1 postfix/submission/smtpd[889279]: lost connection after CONNECT from web2.tld.org[10.10.10.121]
Mar  9 00:28:33 mail1 postfix/submission/smtpd[889279]: disconnect from web2.tld.org[10.10.10.112] commands=0/0
`

**Comment by revpriest** [comment]
It uses PHPMailer, which does opportunistic TLS - if the server advertises that it can do TLS, it will use it automatically.

Not sure why it would lose connection though, and of course bugs that don't affect my own set up are hard to diagnose or fix.

It there any error shown in the "last warn" section of the setup?

**Comment by ledufakademy** [comment]
thank you for replying.
i will test again.

**Comment by ledufakademy** [comment]
2022-03-08 23:35:04: Not sending to xxxxxxxxxx@gmail.com today, already passed sending limits. Will do it later

**Comment by ccoenen** [comment]
@ledufakademy did you resolve this? Is it working as intended?

**Comment by ledufakademy** [comment]
> @ledufakademy did you resolve this? Is it working as intended?

unfortunatly , No : we go for Discourse mailinglist mode.

**Comment by revpriest** [comment]
Pushed a new version to the repo and the app-store with an option to select tls/ssl for the mailer plugin.
Hopefully that's good for fixing this.
