### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by FarmingSoul** [revpriest/listman#23]
hello , thanks for all,
but i have a multiple error :

[PHP] Erreur: Undefined property: OCA\Listman\Db\Maillist::$getSuburl at /var/www/vhosts/****/nextcloud/apps/listman/lib/Service/ListmanService.php#120

[PHP] Erreur: Undefined variable $counter at /var/www/vhosts/****/nextcloud/apps/listman/lib/Controller/ListmanController.php#215

[PHP] Erreur: Undefined variable $counter at /var/www/vhosts/****/nextcloud/apps/listman/lib/Controller/ListmanController.php#212

so the module do not work at home :-(

**Comment by revpriest** [comment]
Thanks for the report!

Hopefully the version pushed just now will fix those bugs.

Not even sure what $counter was supposed to do. Removed it.

I think the other one was maybe a capitalisation issue? I'm less sure I've fixed that.

There were other bugs to do with php8.

Hopefully that's got them all.
