### ISSUE TITLE
 Server version 27 or lower is required... is this still maintained?

### ISSUE THREAD

**Issue by Kugeleis** [revpriest/listman#25]
NC version 27 is EOL for months now. 
Is this project still alive?

**Comment by revpriest** [comment]
Yes, it still works as far as I know. Still running on my instance at least, so still working as of 29.0.8 at least.

I guess I should bump the version number or something? But nothing has changed, and nothing seems to need changing.

**Comment by revpriest** [comment]
There you go, bumped the version numbers and did a new release.

Nothing but the version numbers has changed though.
