### ISSUE TITLE
Trim down release tarball size

### ISSUE THREAD

**Issue by aszlig** [revpriest/listman#6]
The top five largest directories in the 20.0.0 release tarball are:

```
305M    node_modules
15M     vendor
3.6M    js
2.2M    build
500K    package-lock.json
```

Only the `package-lock.json` and `js` are really needed for the release, at least unless there is some magic going on that sidetracks Webpack in some way.

Nevertheless, even if that's the case, that 305 MiB directory is clearly a bit too much for this little app, don't you think? :-)

Besides: The release tarball is currently at https://dalliance.net/listman.tar.gz, which makes it hard to fetch an older version. It's probably a good idea to upload each tarball with its version, like this: https://dalliance.net/listman-20.0.0.tar.gz

**Comment by revpriest** [comment]
Good tips, thanks.

Updated my build-release script to exclude node_modules and vendor and build, bumped the version number.

Didn't realize it would be serving the app-store from my server at all, so moved that into a /listman/ directory on the server as well as putting the version number in the filename.

Pushed a new release.
