### ISSUE TITLE
More undefined variables 

### ISSUE THREAD

**Issue by koehn** [revpriest/listman#9]
20.0.3:

```
[PHP] Error: Undefined variable: message at /var/www/html/custom_apps/listman/templates/notfound.php#5

POST /index.phpman/subscribe/sub
from redacted by redacted at 2021-07-16T14:27:23+02:00
```

Maybe you could figure out why your PHP isn’t warning you about undefined variables, because this way isn’t very efficient.

**Comment by revpriest** [comment]
Indeed, but I can't even find the existence of such a setting let alone where it might be set.

This one was broke on my machine too though. Not sure why it wasn't caught before. Thanks, fixed with new version.
